### ISSUE TITLE
[Docs] #1 search in google for something comes back nil

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/docs#15]
```
https://www.google.com/search?q=bacalhau+input-source&oq=bacalhau+input-source&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg80gEIMjU3NWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8
```

Goes to this page -> https://www.google.com/search?q=bacalhau+input-source&oq=bacalhau+input-source&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg80gEIMjU3NWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8#:~:text=InputSource%20Specification,References%20%E2%80%BA%20Job%20Specification

But that's 404.

should be redirected.

**Comment by frrist** [comment]
FWIW nothing in the google search result is 404ing for me
